version: "3"
tasks:
  build:
    desc: Build the vanilla runtime
    cmds:
      - go mod tidy
      - go build -tags "{{.TAGS}}" -o ./target/connect-runtime-vanilla *.go

  test:
    cmds:
      - go run github.com/onsi/ginkgo/v2/ginkgo -r --compilers=4

  docker:local:
    cmds:
      - docker build . -t connect-runtime-wombat:local